### PR TITLE
[BugFix] Fail to add custom stream load table properties

### PR DESCRIPTION
**Pull request by Lyang77**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：
判断有误导致自定义properties无法添加进httpPut的header中

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by banmoy** [comment]
@lyang77 Thanks for the fix. Could you sign the CLA?

**Comment by lyang77** [comment]
> @lyang77 Thanks for the fix. Could you sign the CLA?

image
 我已经同意了这个协议，但是不知道为啥状态还是pending状态

**Comment by Lyang77** [comment]
> @lyang77 Thanks for the fix. Could you sign the CLA?

@banmoy ok

**Comment by banmoy** [comment]
LGTM

**Review by banmoy — APPROVED** [review]

**Pull request merged**
