### PR TITLE
[Bug Fix] Flink 1.13 exactly-once data repeat

### PR DESCRIPTION
**Pull request by lixiaoer666**
With precision semantics, the connector does not need to call flush in the close method.
Because flink fails, it rolls back to the last checkpoint, at which point the data is recalculated.
If you do not clear the data, data duplication will occur.

### CODE REVIEW

**Comment by xlfjcg** [comment]
1.13 don't have finish even，when the data is bounded，if close not call flush,  end of data will lost

**Comment by lixiaoer666** [comment]
> 1.13 don't have finish event，when the data is bounded，if close not call flush, end of data will lost

I added a configuration to deal with this scenario.

**Comment by xlfjcg** [comment]
> > 1.13 don't have finish event，when the data is bounded，if close not call flush, end of data will lost
> 
> I added a configuration to deal with this scenario.

i think this works, but 2pc would be better that this way to fix this problem?

**Comment by lixiaoer666** [comment]
> > > 1.13 don't have finish event，when the data is bounded，if close not call flush, end of data will lost
> > 
> > 
> > I added a configuration to deal with this scenario.
> 
> i think this works, but 2pc would be better that this way to fix this problem?

StarRocks stream load does not support prepare/commit/rollback, so I don't know how to solve this problem with 2PC.

**Comment by xlfjcg** [comment]
> > > > 1.13 don't have finish event，when the data is bounded，if close not call flush, end of data will lost
> > > 
> > > 
> > > I added a configuration to deal with this scenario.
> > 
> > 
> > i think this works, but 2pc would be better that this way to fix this problem?
> 
> StarRocks stream load does not support prepare/commit/rollback, so I don't know how to solve this problem with 2PC.

sr v2.3 support，connector will do next

**Pull request closed without merging**
